@startuml

package "User Service" {
entity User {
    * user_id : UUID [PK]
    --
    username : VARCHAR(50)
    email : VARCHAR(100)
    password_hash : VARCHAR(255)
    created_at : TIMESTAMP
}

entity UserProfile {
    * profile_id : UUID [PK]
    --
    user_id : UUID [FK]
    first_name : VARCHAR(50)
    last_name : VARCHAR(50)
    birthdate : DATE
    bio : TEXT
}

entity UserRole {
    * role_id : UUID [PK]
    --
    user_id : UUID [FK]
    role_name : VARCHAR(20)
    assigned_at : TIMESTAMP
    is_active : BOOLEAN
}

entity Session {
    * session_id : UUID [PK]
    --
    user_id : UUID [FK]
    token : TEXT
    created_at : TIMESTAMP
    expires_at : TIMESTAMP
}

User ||--o{ UserProfile : has
User ||--o{ UserRole : assigned
User ||--o{ Session : owns
}

package "Post Service" {
    entity Post {
    * post_id : UUID [PK]
    --
    user_id : UUID [FK]
    content : TEXT
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
    visibility : VARCHAR(20)
}

entity Comment {
    * comment_id : UUID [PK]
    --
    post_id : UUID [FK]
    user_id : UUID [FK]
    content : TEXT
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity Media {
    * media_id : UUID [PK]
    --
    post_id : UUID [FK]
    media_type : VARCHAR(50)
    url : TEXT
    uploaded_at : TIMESTAMP
}

entity PostLike {
    * like_id : UUID [PK]
    --
    post_id : UUID [FK]
    user_id : UUID [FK]
    liked_at : TIMESTAMP
}

Post ||--o{ Comment : has
Post ||--o{ Media : includes
Post ||--o{ PostLike : receives
}

package "Statistics Service" {
entity PostView {
    * view_id : UUID [PK]
    --
    post_id : UUID [FK]
    user_id : UUID [FK]
    viewed_at : TIMESTAMP
}

entity PostStat {
    * post_id : UUID [PK]
    --
    views_count : INTEGER
    likes_count : INTEGER
    comments_count : INTEGER
    last_updated : TIMESTAMP
}

entity CommentStat {
    * post_id : UUID [FK]
    * comment_id : UUID [PK]
    --
    comment_count : INTEGER
    last_updated : TIMESTAMP
}

Post ||--o{ PostView : has
Post ||--o{ PostStat : has
Comment ||--o{ CommentStat : has
}

User ||--o{ Post : "creates"
User ||--o{ Comment : "writes"

@enduml
