# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statistics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\nstatistics\"\x1e\n\x0bPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"C\n\x11PostStatsResponse\x12\r\n\x05views\x18\x01 \x01(\x04\x12\r\n\x05likes\x18\x02 \x01(\x04\x12\x10\n\x08\x63omments\x18\x03 \x01(\x04\"*\n\x0b\x44ynamicData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"8\n\x0f\x44ynamicResponse\x12%\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x17.statistics.DynamicData\"0\n\nTopRequest\x12\"\n\x06metric\x18\x01 \x01(\x0e\x32\x12.statistics.Metric\")\n\x07TopPost\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"6\n\x10TopPostsResponse\x12\"\n\x05posts\x18\x01 \x03(\x0b\x32\x13.statistics.TopPost\")\n\x07TopUser\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"6\n\x10TopUsersResponse\x12\"\n\x05users\x18\x01 \x03(\x0b\x32\x13.statistics.TopUser*,\n\x06Metric\x12\t\n\x05VIEWS\x10\x00\x12\t\n\x05LIKES\x10\x01\x12\x0c\n\x08\x43OMMENTS\x10\x02\x32\xc3\x03\n\x11StatisticsService\x12\x46\n\x0cGetPostStats\x12\x17.statistics.PostRequest\x1a\x1d.statistics.PostStatsResponse\x12G\n\x0fGetViewsDynamic\x12\x17.statistics.PostRequest\x1a\x1b.statistics.DynamicResponse\x12G\n\x0fGetLikesDynamic\x12\x17.statistics.PostRequest\x1a\x1b.statistics.DynamicResponse\x12J\n\x12GetCommentsDynamic\x12\x17.statistics.PostRequest\x1a\x1b.statistics.DynamicResponse\x12\x43\n\x0bGetTopPosts\x12\x16.statistics.TopRequest\x1a\x1c.statistics.TopPostsResponse\x12\x43\n\x0bGetTopUsers\x12\x16.statistics.TopRequest\x1a\x1c.statistics.TopUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRIC']._serialized_start=483
  _globals['_METRIC']._serialized_end=527
  _globals['_POSTREQUEST']._serialized_start=32
  _globals['_POSTREQUEST']._serialized_end=62
  _globals['_POSTSTATSRESPONSE']._serialized_start=64
  _globals['_POSTSTATSRESPONSE']._serialized_end=131
  _globals['_DYNAMICDATA']._serialized_start=133
  _globals['_DYNAMICDATA']._serialized_end=175
  _globals['_DYNAMICRESPONSE']._serialized_start=177
  _globals['_DYNAMICRESPONSE']._serialized_end=233
  _globals['_TOPREQUEST']._serialized_start=235
  _globals['_TOPREQUEST']._serialized_end=283
  _globals['_TOPPOST']._serialized_start=285
  _globals['_TOPPOST']._serialized_end=326
  _globals['_TOPPOSTSRESPONSE']._serialized_start=328
  _globals['_TOPPOSTSRESPONSE']._serialized_end=382
  _globals['_TOPUSER']._serialized_start=384
  _globals['_TOPUSER']._serialized_end=425
  _globals['_TOPUSERSRESPONSE']._serialized_start=427
  _globals['_TOPUSERSRESPONSE']._serialized_end=481
  _globals['_STATISTICSSERVICE']._serialized_start=530
  _globals['_STATISTICSSERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
